{
 "title": "Storage pool claim dashboard",
 "tags": [ "OpenEBS" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "spc",
    "label": "Storage pool",
    "query": "label_values(openebs_pool_status,storage_pool_claim)"
   },
   {
    "name": "Pool",
    "label": "Pool",
    "query": "label_values(openebs_pool_status{storage_pool_claim=~\"$spc\"},cstor_pool)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "openebs_pool_status{cstor_pool=~\"$Pool\"}",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Size of  pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "openebs_pool_size{cstor_pool=~\"$Pool\"}/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Used pool capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_used_pool_capacity{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Free pool capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_free_pool_capacity{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_read_count{cstor_pool=~\"$Pool\"}) by (cstor_pool)",
     "legendFormat": "{{cstor_pool}}"
    },
    { "legendFormat": "write iops" }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_write_count{cstor_pool=~\"$Pool\"}) by (cstor_pool)",
     "legendFormat": "{{cstor_pool}}"
    }
   ]
  }
 ]
}