{
 "title": "Storage pool dashboard",
 "tags": [ "OpenEBS" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pool",
    "label": "Pool",
    "query": "label_values(openebs_pool_status{cstor_pool=~\"$pool\"},cstor_pool)"
   },
   {
    "name": "spc",
    "label": "spc",
    "query": "label_values(openebs_pool_status{cstor_pool=~\"$Pool\"},storage_pool_claim)"
   },
   { "name": "pool", "label": "pool" },
   { "name": "kind", "label": "kind" }
  ]
 },
 "panels": [
  {
   "title": "Pool information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<html>\n<head>\n\n<script>\nwindow.onload = load('$Pool', '$spc','$kind');\n\nfunction getCell(name, value) {\n  return \"<div class=\\\"outlet-header-meta-bar_item\\\"><div class=\\\"outlet-header-meta-bar_title\\\"><span>\"+name+\"</span></div><div class=\\\"outlet-header-meta-bar_value\\\"><span>\"+value+\"</span></div></div>\";\n}\n\nfunction load(poolNameStr, spcStr,kindStr) {\nvar poolNameStr = poolNameStr.replace( /[{}]/g, '' );\nvar spcStr = spcStr.replace( /[{}]/g, '' );\nvar kindStr = kindStr.replace( /[{}]/g, '' );\n// var pools = poolsStr.replace( /[{}]/g, '' );\n// var rc = replicaCount.replace( /[{}]/g, '' );\n// if(!rc) {\n//   rc = \"none\";\n// }\n// var uptimes = uptime.replace( /[{}]/g, '' );\n// if(uptimes) {\n// var seconds = parseInt(uptimes, 10);\n\n// var days = Math.floor(seconds / (3600*24));\n// seconds  -= days*3600*24;\n// var hrs   = Math.floor(seconds / 3600);\n// seconds  -= hrs*3600;\n// var mnts = Math.floor(seconds / 60);\n// seconds  -= mnts*60;\n// uptimes = days+\" days, \"+hrs+\" Hrs, \"+mnts+\" Mins, \"+seconds+\" Secs\";\n// }\n// else {\n//   uptimes = \"No Data\";\n// }\n\n\n\nz=\"\";\nz+=getCell(\"Pool Name\", poolNameStr);\n//z+=getCell(\"Name\", volName);\nz+=getCell(\"Pool Name\", pools);\n//z+=getCell(\"No. of Replicas\", rc);\n//z+=getCell(\"\",\"\")\n\ndocument.getElementById(\"volume-info\").innerHTML = z;\n}\n</script>\n</head>\n\n<body>\n\n<div id=\"volume-info\" class=\"outlet-header-bar\"></div>\n\n</body>\n\n</html>"
  },
  {
   "title": "Pool status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "openebs_pool_status{cstor_pool=~\"$Pool\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Size of  pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_pool_size{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "total size"
    }
   ]
  },
  {
   "title": "Used pool capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_used_pool_capacity{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Free pool capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_free_pool_capacity{cstor_pool=~\"$Pool\"})/(1024*1024*1024)",
     "legendFormat": "free size"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_read_count{cstor_pool=~\"$Pool\"})",
     "legendFormat": "read iops"
    },
    { "legendFormat": "write iops" }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_write_count{cstor_pool=~\"$Pool\"})",
     "legendFormat": "write iops"
    }
   ]
  }
 ]
}