{
 "title": "Cluster Volumes Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Cluster:",
    "query": "label_values(openebs_size_of_volume,job)"
   },
   {
    "name": "openebs_Volume",
    "label": "Volume",
    "query": "label_values(openebs_size_of_volume{job=~\".*$job.*\"},openebs_pv)"
   },
   {
    "name": "openebs_pvc",
    "label": "OpenEBS pvc",
    "query": "label_values(openebs_size_of_volume{job=~\".*$job.*\",openebs_pv=~\"$openebs_Volume\"},openebs_pvc)"
   },
   { "name": "projectid", "label": "projectid" },
   { "name": "groupid", "label": "groupid" }
  ]
 },
 "panels": [
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "openebs_actual_used{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "IOPS(Reads)",
   "type": "graph",
   "description": "IOPS",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(openebs_reads{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "IOPS(Writes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(openebs_writes{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Throughput(Reads)",
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(openebs_read_block_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])/(2048)",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Throughput(Writes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(openebs_write_block_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])/(2048)",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Latency(Reads)",
   "type": "graph",
   "description": "Latency",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "((irate(openebs_read_time{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m]))/(irate(openebs_reads{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])))/1000000",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Latency(Writes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "((irate(openebs_write_time{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m]))/(irate(openebs_writes{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])))/1000000",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Block Size(Reads)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(irate(openebs_read_block_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])/(1024))*512/(irate(openebs_reads{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m]))",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Block Size(Writes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(irate(openebs_write_block_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])/(1024))*512/(irate(openebs_writes{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m]))",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  }
 ]
}