{
 "title": "Volume workload report",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Cluster_uuid",
    "label": "Cluster",
    "query": "label_values(openebs_size_of_volume,job)"
   },
   {
    "name": "openebs_Volume",
    "label": "Volume",
    "query": "label_values(openebs_size_of_volume{job=~\".*$Cluster_uuid.*\"},openebs_pv)"
   },
   {
    "name": "openebs_pvc",
    "label": "Openebs pvc",
    "query": "label_values(openebs_size_of_volume{job=~\".*$Cluster_uuid.*\",openebs_pv=~\"$openebs_Volume\"},openebs_pvc)"
   },
   { "name": "projectid", "label": "projectid" },
   { "name": "groupid", "label": "groupid" }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(irate(openebs_reads{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m]))+(irate(openebs_writes{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m]))",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(irate(openebs_read_block_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])/(2048)) + (irate(openebs_write_block_count{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}[5m])/(2048))",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "openebs_actual_used{openebs_pvc=~\"$openebs_pvc\",openebs_pv=~\"$openebs_Volume\"}",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  }
 ]
}